---
name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install uv
        uses: actions/setup-uv@803947b9bd8e9f986429fa0c5a41c367cd732b41 # v7

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Lint
        run: uv run ruff check .

      - name: Format check
        run: uv run ruff format --check .

      - name: Type check
        run: uv run basedpyright tootlogger/

      - name: Test
        run: uv run pytest tests/
