---
name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install uv
        uses: actions/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Lint
        run: uv run ruff check .

      - name: Format check
        run: uv run ruff format --check .

      - name: Type check
        run: uv run basedpyright tootlogger/

      - name: Test
        run: uv run pytest tests/
